pipeline {
    agent any
    tools {
        go "go-1.23.2"
    }

    environment {
        GO111MODULE="on"
    }

    stages {
        stage("Test") {
            steps {
                git "https://github.com/ybkuroki/go-webapp-sample.git"
                sh "go test ./..."
            }
        }
    }
}