print("Hello, \nfuture Python programmer")
print("Python is a great language")
print("Hello", "future", "Python", "programmer")
print("Hello", end="")
print("Hello", "future", "Python", "programmer", sep=";")