pipeline {
    agent any
    tools {
        go "go-1.23.2"
    }

    environment {
        GO111MODULE="on"
    }

    stages {
        stage("test") {
            steps {
                git "https://github.com/ybkuroki/go-webapp-sample.git"
                sh "go test ./..."
            }
        }

        stage("Build") {
            steps {
                git "https://github.com/ybkuroki/go-webapp-sample.git"
                sh 'go build .'
            }
        }

        stage("Run") {
            steps {
                sh "cd /var/lib/jenkins/workspace/go-full-pipeline && go-webapp-sample &"
            }
        }
    }
}