apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    type: frontend
spec:
  template:
    metadata:
      name: httpd
      labels:
        type: frontend
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
  selector:
    matchLabels:
      type: frontend
  replicas: 3